/**
 * 自動選択ループ(SmartGenerationLoop)が過去の実績からの「推測」で自動評価して書き込んだ履歴に
 * 付くタグ。ユーザーが実際に評価したものではないため、これを自己学習系の集計
 * (ランキング/お気に入り組み合わせ/キーワード学習/テンポ学習/新語彙発見)に混ぜると、
 * ループが自分自身の推測を再学習し続ける閉じたフィードバックループになり、
 * 同じ組み合わせへの収束や評価の停滞(★3固定)を招く。
 * そのため、これらの集計対象からは常に除外する(履歴一覧自体には残るので後から手動で見返し・再評価できる)。
 */
export const SMART_LOOP_TAG = '自動選択ループ'

export function excludeAutoGeneratedEntries<T extends { tags: string[] }>(entries: T[]): T[] {
  return entries.filter((e) => !e.tags.includes(SMART_LOOP_TAG))
}
